expensecounter/ExpenseCounterApp/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name="ExpenseCounterApp"
urlpatterns = [
    path('', views.index),
    path('setlanguage/<str:setlanguage>', views.set_language, name='set-language'),
    path('index', views.index, name="index"),
    path('deleteitem/<int:dbkey>', views.deleteitem),
    path('test', views.test, name="testy"),
]

expensecounter/expensecounter/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ExpenseCounterApp.urls')),
]

expensecounter/ExpenseCounterApp/models.py
from django.db import models

# Create your models here.

class expense_item(models.Model):
    category = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=400)
    cost = models.DecimalField(max_digits=9, decimal_places=2)
    purchase_time = models.DateTimeField('time purchased')
    time_added = models.DateTimeField('time added') #when this was added to this database
    def toString():
        finishedString = category
        finishedString += ", "
        finishedString += name
        finishedString += ", "
        finishedString += cost
        
    def __str__(self):
        return toString()

expensecounter/ExpenseCounterApp/views.py
import datetime
from decimal import *

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import expense_item
from django.utils import timezone

from django.core import management #In case the database needs to be built
# Create your views here.

debugLog = {}

strings_en = {"appTitle": "Expense Counter",
"breakdown_header": "Total breakdown:",
"newitem_header": "Add something:",
"item_list_header": "Expense items:",

"food_grocery_text": "Food: Grocery",
"food_takeout_text": "Food: Takeout",
"food_convenience_text": "Food: Convenience Store",
"one_time_important_text": "One Time Expense (Important)",
"one_time_unimportant_text": "One Time Expense (Unimportant)",
"recurring_important_text": "Recurring Expense (Important)",
"recurring_unimportant_text": "Recurring Expense (Unimportant)",
"total_spend_text": "Total spend",

"date_form_start_date": "Start date:",
"date_form_end_date": "End date:",

"newitem_form_category": "Category:",
"newitem_form_name": "Name:",
"newitem_form_description": "Description:",
"newitem_form_cost": "Cost:",
"newitem_form_time_purchased": "Bought on:",
"newitem_form_time_added": "Added on:",

"button_go": "Go",
"button_submit": "Submit",
"button_delete": "Delete",

"no_purchases": "You haven't bought anything! That's very fiscally responsible."}

strings_jp = {"appTitle": "費用カウンタ",
"breakdown_header": "費用分配:",
"newitem_header": "要素を追加:",
"item_list_header": "内訳:",

"food_grocery_text": "食べ物：グロセリー",
"food_takeout_text": "食べ物：テイクアウト",
"food_convenience_text": "食べ物：コンビニ",
"one_time_important_text": "一回の費用 (大切)",
"one_time_unimportant_text": "一回の費用 (大切ない)",
"recurring_important_text": "経常費 (大切)",
"recurring_unimportant_text": "経常費 (大切ない)",
"total_spend_text": "総",

"date_form_start_date": "始めのデート:",
"date_form_end_date": "終了のデート:",

"newitem_form_category": "カテゴリー:",
"newitem_form_name": "物:",
"newitem_form_description": "説明:",
"newitem_form_cost": "お値段:",
"newitem_form_time_purchased": "買い時:",
"newitem_form_time_added": "追加時:",

"button_go": "投入",
"button_submit": "投入",
"button_delete": "消す",

"no_purchases": "買い物ありません！おめでとうございます。"}

appTitle = "Expense Counter" #app name displayed to the user
language = "english" #reference when deciding which language dict to load

def index(request):
    
    template = loader.get_template('ExpenseCounterApp/index.html')
    
    try:
        two_weeks_ago_interval = datetime.timedelta(days=14)
        two_weeks_ago = timezone.now() - two_weeks_ago_interval
        date_range_start = format_date_for_html(two_weeks_ago)
        date_range_end = format_date_for_html(timezone.now())
        ordered_db = expense_item.objects.filter(purchase_time__range=[date_range_start, date_range_end])
        total_spend = get_total_spend(date_range_start, date_range_end, "all")
    except:
        print("Exception thrown in views.index(request); database may not be initialized. Migrations will be applied and the page will be reloaded.")
        management.call_command("makemigrations")
        management.call_command("migrate", "--run-syncdb")
        return index(request)
        
    
    context = {'expense_items': ordered_db,
                'worked': "Default value",
                'app_title': appTitle,
                'date_range_start': date_range_start,
                'date_range_end': date_range_end,
                'breakdown_percents': get_percents(date_range_start, date_range_end),
                'today': timezone.now(),
                'strings': strings_en,
                'total_spend': total_spend}
                
    if (language == "english"): 
        context['strings'] = strings_en
        print("ENGLISH")
    if (language == "japanese"): 
        context['strings'] = strings_jp
        print("JAPAN")
    
    if request.method == "POST": #add item
        if request.POST.get('name'):
            newitem = expense_item()
            newitem.category = request.POST.get('categoryDropDown')
            newitem.name = request.POST.get('name')
            newitem.description = request.POST.get('description')
            newitem.cost = request.POST.get('cost')
            newitem.purchase_time = request.POST.get('purchase_time')
            newitem.time_added = timezone.now()
            
            newitem.save()
            context['worked'] = "POST data was sent"
            context['breakdown_percents'] = get_percents(date_range_start, date_range_end)
            context['total_spend'] = get_total_spend(date_range_start, date_range_end, "all")
            
            return HttpResponse(template.render(context, request))
            
        if request.POST.get('startDate'): #change date view
        #format_date_for_html isn't necessary here because the dates are being read from the form in the POST data, so they're already formatted correctly
            date_range_start = request.POST.get('startDate')
            date_range_end = request.POST.get('endDate')
            
            ordered_db = expense_item.objects.filter(purchase_time__range=[date_range_start, date_range_end])
            context['date_range_start'] = date_range_start
            context['date_range_end'] = date_range_end
            context['expense_items'] = ordered_db
            context['breakdown_percents'] = get_percents(date_range_start, date_range_end)
            
            print("Start date:" + date_range_start)
            print("End date:" + date_range_end)
            context['worked'] = "Date range POST data was sent"
            context['total_spend'] = get_total_spend(date_range_start, date_range_end, "all")
            
            percents = get_percents(date_range_start, date_range_end)
            
            return HttpResponse(template.render(context, request))
    
    context['worked'] = "No POST data was sent"
    return HttpResponse(template.render(context, request))
    
def deleteitem(request, dbkey):
    object = expense_item.objects.get(id=dbkey)
    logoutput("Deleting: " + object.name)
    object.delete()
    return redirect('/index')

#Valid languages are "english" and "japanese"
def set_language(request, setlanguage):
    if (setlanguage == "english" or setlanguage == "japanese"):
        global language
        language = setlanguage
    return redirect('/index')
    
def test(request):
    return HttpResponse("Hello")


                #Things that aren't views:


#Use this to format dates before being sent to a template for use in a date input
#This prevents us from having to treat dates differently whether they're passed to a template as a
#python datetime or as already formatted for HTML (ie if they came from POST data & were then sent
#back to another template)
def format_date_for_html(date):
    month = str(date.month)
    if len(month) == 1:
        month = str(0) + month
    
    day = str(date.day)
    if len(day) == 1:
        day = str(0) + day
    
    date_formatted = str(date.year) + "-" + month + "-" + day
    return date_formatted


#Get a dict of the percentage breakdown of these categories:
#food_grocery, food_takeout, food_convenience, one_time_important, one_time_unimportant
#recurring_important, #recurring_unimportant
def get_percents(date_range_start, date_range_end):
    debug = False
    total_spend = get_total_spend(date_range_start, date_range_end, "all")
    breakdown = {'food_grocery': Decimal(0),
    'food_takeout': Decimal(0),
    'food_convenience': Decimal(0),
    'one_time_important': Decimal(0),
    'one_time_unimportant': Decimal(0),
    'recurring_important': Decimal(0),
    'recurring_unimportant': Decimal(0)}
    
    if total_spend == 0: return breakdown;
    
    
    breakdown['food_grocery'] = (get_total_spend(date_range_start, date_range_end, "food_grocery") / total_spend) * 100
    breakdown['food_takeout'] = Decimal((get_total_spend(date_range_start, date_range_end, "food_takeout")) / Decimal(total_spend)) * Decimal(100)
    breakdown['food_convenience'] = (get_total_spend(date_range_start, date_range_end, "food_convenience") / total_spend) * 100
    breakdown['one_time_important'] = get_total_spend(date_range_start, date_range_end, "one_time_important") / total_spend * 100
    breakdown['one_time_unimportant'] = get_total_spend(date_range_start, date_range_end, "one_time_unimportant") / total_spend * 100
    breakdown['recurring_important'] = get_total_spend(date_range_start, date_range_end, "recurring_important") / total_spend * 100
    breakdown['recurring_unimportant'] = get_total_spend(date_range_start, date_range_end, "recurring_unimportant") / total_spend * 100
    
    if (debug): print("The breakdown: " + str(breakdown['food_grocery']) + " " + str(breakdown['food_takeout']) + " " + str(breakdown['food_convenience']) + " " + str(breakdown['one_time_important']) + " " + str(breakdown['one_time_unimportant']) + " " + str(breakdown['recurring_important']) + " " + str(breakdown['recurring_unimportant']))
    
    if (str(breakdown['food_grocery']).find('.') > -1): 
        breakdown['food_grocery'] = str(breakdown['food_grocery'])[0:str(breakdown['food_grocery']).find('.') + 2]
        
    if (str(breakdown['food_takeout']).find('.') > -1): 
        breakdown['food_takeout'] = str(breakdown['food_takeout'])[0:str(breakdown['food_takeout']).find('.') + 2]
        
    if (str(breakdown['food_convenience']).find('.') > -1): 
        breakdown['food_convenience'] = str(breakdown['food_convenience'])[0:str(breakdown['food_convenience']).find('.') + 2]
        
    if (str(breakdown['one_time_important']).find('.') > -1): 
        breakdown['one_time_important'] = str(breakdown['one_time_important'])[0:str(breakdown['one_time_important']).find('.') + 2]
        
    if (str(breakdown['one_time_unimportant']).find('.') > -1): 
        breakdown['one_time_unimportant'] = str(breakdown['one_time_unimportant'])[0:str(breakdown['one_time_unimportant']).find('.') + 2]

expensecounter/ExpenseCounterApp/templates/ExpenseCounterApp/index.html
{% load static %}
<html>
<head>
	<link rel="stylesheet" href="{% static 'expensecounterapp_index.css' %}">
	<script>
		var csstime = document.querySelector(':root');
		var computedstyles = getComputedStyle(csstime);
		var sizemultiple = 1.6;
		
		var foodGrocerySize = {{ breakdown_percents.food_grocery }};
		var foodTakeoutSize = {{ breakdown_percents.food_takeout }};
		var foodConvenienceSize = {{ breakdown_percents.food_convenience }};
		var oneTimeImportantSize = {{ breakdown_percents.one_time_important }};
		var oneTimeUnimportantSize = {{ breakdown_percents.one_time_unimportant }};
		var recurringImportantSize = {{ breakdown_percents.recurring_important }};
		var recurringUnimportantSize = {{ breakdown_percents.recurring_unimportant }};
		
		
		if (foodGrocerySize < computedstyles.getPropertyValue('--default-percent-size')){
			foodGrocerySize = computedstyles.getPropertyValue('--default-percent-size');
		}
		else{
			csstime.style.setProperty('--food-grocery-size', {{ breakdown_percents.food_grocery }} * sizemultiple);
		}
		
		if (foodTakeoutSize < computedstyles.getPropertyValue('--default-percent-size')){
			foodTakeoutSize = computedstyles.getPropertyValue('--default-percent-size');
		}
		else{
			csstime.style.setProperty('--food-takeout-size', {{ breakdown_percents.food_takeout }} * sizemultiple);
		}
		
		if (foodConvenienceSize < computedstyles.getPropertyValue('--default-percent-size')){
			foodConvenienceSize = computedstyles.getPropertyValue('--default-percent-size');
		}
		else{
			csstime.style.setProperty('--food-convenience-size', {{ breakdown_percents.food_convenience }} * sizemultiple);
		}
		
		if (oneTimeImportantSize < computedstyles.getPropertyValue('--default-percent-size')){
			oneTimeImportantSize = computedstyles.getPropertyValue('--default-percent-size');
		}
		else{
			csstime.style.setProperty('--one-time-important-size', {{ breakdown_percents.one_time_important }} * sizemultiple);
		}
		
		if (oneTimeUnimportantSize < computedstyles.getPropertyValue('--default-percent-size')){
			oneTimeUnimportantSize = computedstyles.getPropertyValue('--default-percent-size');
		}
		else{
			csstime.style.setProperty('--one-time-unimportant-size', {{ breakdown_percents.one_time_unimportant }} * sizemultiple);
		}
		
		if (recurringImportantSize < computedstyles.getPropertyValue('--default-percent-size')){
			recurringImportantSize = computedstyles.getPropertyValue('--default-percent-size');
		}
		else{
			csstime.style.setProperty('--recurring-important-size', {{ breakdown_percents.recurring_important }} * sizemultiple);
		}
		
		if (recurringUnimportantSize < computedstyles.getPropertyValue('--default-percent-size')){
			recurringUnimportantSize = computedstyles.getPropertyValue('--default-percent-size');
		}
		else{
			csstime.style.setProperty('--recurring-unimportant-size', {{ breakdown_percents.recurring_unimportant }} * sizemultiple);
		}
		
	</script>
</head>
<body>
<div id="pagecontainer">
	<header>
	<div id="language-select"><a href="{% url 'ExpenseCounterApp:set-language' 'english' %}">En</a> / <a href="{% url 'ExpenseCounterApp:set-language' 'japanese' %}">Jp</a></div>
	<h1 id = "appTitle">{{ strings.appTitle }}</h1>
	</header>
	<br><br>
	
	<form action="" method="POST" id = "dateform">
		{% csrf_token %}
			<div class="datelabel"><label for="startDate">{{ strings.date_form_start_date }}</label><input name="startDate" type="date" value="{{ date_range_start }}"></div>
			<div class="datelabel"><label for="endDate">{{ strings.date_form_end_date }}</label><input name="endDate" type="date" value="{{ date_range_end }}">
			<input type="submit" value="{{ strings.button_go }}"></div>
	</form>

	<h3>{{ strings.breakdown_header }}</h3><br>
	<div id="percentages-display">
		<div class="breakdown-item-container"><div name="percentageDisplayLine">{{ strings.food_grocery_text }}:</div><div id="food-grocery-percent">{{ breakdown_percents.food_grocery }}%</div></div>
		
		<div class="breakdown-item-container"><div name="percentageDisplayLine">{{ strings.food_takeout_text }}:</div><div id="food-takeout-percent">{{ breakdown_percents.food_takeout }}% </div></div>
		
		<div class="breakdown-item-container"><div name="percentageDisplayLine">{{ strings.food_convenience_text }}:</div><div id="food-convenience-percent">{{ breakdown_percents.food_convenience }}%</div></div>
		
		<div class="breakdown-item-container"><div name="percentageDisplayLine">{{ strings.one_time_important_text }}:</div><div id="one-time-important-percent">{{ breakdown_percents.one_time_important }}%</div></div>
		
		<div class="breakdown-item-container"><div name="percentageDisplayLine">{{ strings.one_time_unimportant_text }}:</div><div id="one-time-unimportant-percent">{{ breakdown_percents.one_time_unimportant }}%</div></div>
		
		<div class="breakdown-item-container"><div name="percentageDisplayLine">{{ strings.recurring_important_text}}:</div><div id="recurring-important-percent">{{ breakdown_percents.recurring_important }}%</div></div>
		
		<div class="breakdown-item-container"><div name="percentageDisplayLine">{{ strings.recurring_unimportant_text }}:</div><div id="recurring-unimportant-percent">{{ breakdown_percents.recurring_unimportant }}%</div></div>
		
		<div class="breakdown-item-container">{{ strings.total_spend_text }}:<div id="total-spend-value"> ${{ total_spend }}</div></div>
	</div>

	<br><br>

	<div id="new-item-form"> <!-- Add Something form -->
		<h3>{{ strings.newitem_header }}</h3>
		<form action="" method="POST" class="flex-row">
			{% csrf_token %}
			<div class="flex-row-item">
				<label for="categoryDropDown">{{ strings.newitem_form_category }}</label>
					<select name="categoryDropDown">
						<option value="food_grocery">{{ strings.food_grocery_text }}</option>
						<option value="food_takeout">{{ strings.food_takeout_text }}</option>
						<option value="food_convenience">{{ strings.food_convenience_text }}</option>
						<option value="one_time_important">{{ strings.one_time_important_text }}</option>
						<option value="one_time_unimportant">{{ strings.one_time_unimportant_text }}</option>
						<option value="recurring_important">{{ strings.recurring_important_text }}</option>
						<option value="recurring_unimportant">{{ strings.recurring_unimportant_text }}</option>
					</select>
				</label>
			</div>
			<br>
			<label for="name">{{ strings.newitem_form_name }}</label><br>
			<input type="text" name="name"/><br>
			
			<label for="description">{{ strings.newitem_form_description }}</label><br>
			<input type="text" name="description"/><br>
			
			<label for="cost">{{ strings.newitem_form_cost }}</label><br>
			<input type="number" name="cost" step="any" class="costinput"/><br>
			
			<label for="purchase_time">{{ strings.newitem_form_time_purchased }}</label>
			<input type="date" name="purchase_time" value="{{ today|date:'Y-m-d' }}"/><br>
			
			<br>
			<input type="submit" value="{{ strings.button_submit }}">
		</form>
	</div>

	<br><br>

	<div id="itemList">
		<h3>{{ strings.item_list_header }}</h3> <!-- Expense items: -->
		<br>
		{% if expense_items %}
			<ul>
			{% for expense_item in expense_items %}
				<li>{# {{expense_item.category}} #}
				{% if expense_item.category == "food_grocery" %}<div class="food-grocery-color">{{ strings.food_grocery_text }}
				{% elif expense_item.category == "food_takeout" %}<div class="food-takeout-color">{{ strings.food_takeout_text }}
				{% elif expense_item.category == "food_convenience" %}<div class="food-convenience-color">{{ strings.food_convenience_text }}
				{% elif expense_item.category == "one_time_important" %}<div class="one-time-important-color">{{ strings.one_time_important_text }}
				{% elif expense_item.category == "one_time_unimportant" %}<div class="one-time-unimportant-color">{{ strings.one_time_unimportant_text }}
				{% elif expense_item.category == "recurring_important" %}<div class="recurring-important-color">{{ strings.recurring_important_text }}
				{% elif expense_item.category == "recurring_unimportant" %}<div class="recurring-unimportant-color">{{ strings.recurring_unimportant_text}}
				{% endif %}</div>
				${{ expense_item.cost }} {{ expense_item.name }} "{{ expense_item.description }}" 
				{{ strings.newitem_form_time_purchased }} {{ expense_item.purchase_time|date:'m-d-y' }} {{ strings.newitem_form_time_added }} {{ expense_item.time_added }}
				<form action="deleteitem/{{ expense_item.pk }}" method="POST">
					{% csrf_token %} 
					<input type="submit" value="{{ strings.button_delete }}">
				</form>
				</li>
			{% endfor %}
			</ul>
		{% else %}
			{{ strings.no_purchases }} <!-- You haven't bought anything! That's very fiscally responsible. -->
		{% endif %}
	</div>

	<footer>
		<div name="debugBox">
			<h4>Debug Info</h4><br>
			{{ worked }} <br>
			
		</div>
	</footer>
</div>
</body>
</html>